{% set version = "2.17.1" %}

package:
  name: git
  version: {{ version }}

source:
  url: https://github.com/git/git/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 690f12cc5691e5adaf2dd390eae6f5acce68ae0d9bd9403814f8a1433833f02a  # [not win]

  url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-64-bit.7z.exe  # [win64]
  sha256: bbf03185afa4a38390ae44d2780aa90d9052975f3be2f1b6a7f43231628a7de6  # [win64]

build:
  number: 0
  skip: true  # [win and not py27]
  # git hardcodes paths to external utilities (e.g. curl)
  detect_binary_files_with_prefix: true

requirements:
  build:
    - autoconf        # [unix]
    - curl >=7.44.0,<8  # [unix]
    - expat 2.2.*           # [unix]
    - libiconv 1.15        # [unix]
    - openssl 1.0.*   # [unix]
    - zlib 1.2.11      # [unix]
    - 7za             # [win]

    # Workaround for conda-build issue.
    - python          # [win]
  run:
    - curl >=7.44.0,<8  # [unix]
    - expat 2.2.*           # [unix]
    - libiconv 1.15        # [unix]
    - openssl 1.0.*   # [unix]
    - zlib 1.2.11      # [unix]

test:
  commands:
    # Verify git location.
    - test -f $PREFIX/bin/git                               # [unix]
    - if not exist %LIBRARY_PREFIX%\\bin\\git.exe exit 1    # [win]

    # Run git commands.
    - git --version
    - git clone https://github.com/conda-forge/git-feedstock

    # test completions
    - bash $PREFIX/share/bash-completion/completions/git  # [unix]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://git-scm.com/
  license: GPL v2 and LGPL 2.1
  summary: distributed version control system

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - scopatz
    - ocefpaf
